FITBIT_CONSUMER_KEY: 56d1356a33db48c68f211d2507d93497
FITBIT_CONSUMER_SECRET: 94d3834447df4944814130fcdf04e8f8
FITBIT_CLIENT_ID: 229BZ3

SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
SLACK_WEBHOOK_CHANNEL: #exceptions
SLACK_WEBHOOK_USERNAME: FitSense API

AZURE_STORAGE_ACCOUNT: rubyonrailsubuntu7531
AZURE_STORAGE_ACCESS_KEY: EdnfYnOCOCpnQRNEoSDsEhoWcEFbHsE0CEyoa50GnTX6lsquDNIo667+v3dnxoeYdFsClxz6AhSobzgZIOpz+A==